spring.application.name=backend

server.port=${SERVER_PORT:8080}

# ===============================
# DATASOURCE / POSTGRESQL
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/backend_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:backend_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# AUTH0 / JWT RESOURCE SERVER
# ===============================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI:https://TU-DOMINIO.auth0.com/}
auth0.audience=${AUTH0_AUDIENCE:https://api.proyecto.backend}

# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE